Traceback (most recent call last):
  File "C:\Users\Alexander\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Alexander\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Image(filename = "/workspace/assets/voxel.png", width=1000, height=800)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32mC:\Users\ALEXAN~1\AppData\Local\Temp/ipykernel_5620/926435947.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mImage[0m[1;33m([0m[0mfilename[0m [1;33m=[0m [1;34m"/workspace/assets/voxel.png"[0m[1;33m,[0m [0mwidth[0m[1;33m=[0m[1;36m1000[0m[1;33m,[0m [0mheight[0m[1;33m=[0m[1;36m800[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\anaconda3\lib\site-packages\IPython\core\display.py[0m in [0;36m__init__[1;34m(self, data, url, filename, format, embed, width, height, retina, unconfined, metadata)[0m
[0;32m   1229[0m         [0mself[0m[1;33m.[0m[0mretina[0m [1;33m=[0m [0mretina[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1230[0m         [0mself[0m[1;33m.[0m[0munconfined[0m [1;33m=[0m [0munconfined[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1231[1;33m         super(Image, self).__init__(data=data, url=url, filename=filename, 
[0m[0;32m   1232[0m                 metadata=metadata)
[0;32m   1233[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\IPython\core\display.py[0m in [0;36m__init__[1;34m(self, data, url, filename, metadata)[0m
[0;32m    635[0m             [0mself[0m[1;33m.[0m[0mmetadata[0m [1;33m=[0m [1;33m{[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m
[0;32m    636[0m [1;33m[0m[0m
[1;32m--> 637[1;33m         [0mself[0m[1;33m.[0m[0mreload[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    638[0m         [0mself[0m[1;33m.[0m[0m_check_data[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    639[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\IPython\core\display.py[0m in [0;36mreload[1;34m(self)[0m
[0;32m   1261[0m         [1;34m"""Reload the raw data from file or URL."""[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1262[0m         [1;32mif[0m [0mself[0m[1;33m.[0m[0membed[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1263[1;33m             [0msuper[0m[1;33m([0m[0mImage[0m[1;33m,[0m[0mself[0m[1;33m)[0m[1;33m.[0m[0mreload[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1264[0m             [1;32mif[0m [0mself[0m[1;33m.[0m[0mretina[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1265[0m                 [0mself[0m[1;33m.[0m[0m_retina_shape[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\IPython\core\display.py[0m in [0;36mreload[1;34m(self)[0m
[0;32m    660[0m         [1;34m"""Reload the raw data from file or URL."""[0m[1;33m[0m[1;33m[0m[0m
[0;32m    661[0m         [1;32mif[0m [0mself[0m[1;33m.[0m[0mfilename[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 662[1;33m             [1;32mwith[0m [0mopen[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mfilename[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0m_read_flags[0m[1;33m)[0m [1;32mas[0m [0mf[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    663[0m                 [0mself[0m[1;33m.[0m[0mdata[0m [1;33m=[0m [0mf[0m[1;33m.[0m[0mread[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    664[0m         [1;32melif[0m [0mself[0m[1;33m.[0m[0murl[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/workspace/assets/voxel.png'
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/assets/voxel.png'

